# Use the official Node.js image as the base image.
FROM node:14

# Set the working directory inside the container.
WORKDIR /usr/src/app

# Install app dependencies.
COPY package*.json ./
RUN npm install

# Copy the rest of the application code to the working directory.
COPY . .

# Build the NestJS application.
RUN npm run build

# Expose the port the app runs on.
EXPOSE 8000

# Define the command to run the application.
CMD ["node", "dist/main.ts"]
